Repository TEAM-DHS/dhs-server, pull requests merged in 2023-11, with the labels that each got.

#4 [DEPLOY] 프로젝트 배포
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/deploy.yml
  .gitignore
  config/nginx/nginx.conf
  docker/Dockerfile
  docker/docker-compose.dev.yml
  docker/docker-compose.prod.yml
Labels: 🔫 배포

#7 [FEAT] Swagger 적용
  build.gradle
  src/main/java/com/efub/dhs/domain/program/entity/Notice.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/global/config/OpenApiConfig.java
  src/main/java/com/efub/dhs/global/entity/BaseTimeEntity.java
Labels: 🔧 기능

#8 [FEAT] Spring Security 기본 설정
  build.gradle
  src/main/java/com/efub/dhs/global/config/AuthenticationConfig.java
Labels: 🐞 버그

#9 [FEAT] 사용자 인증 기능 추가
  build.gradle
  docker/docker-compose.dev.yml
  src/main/java/com/efub/dhs/domain/member/controller/AuthController.java
  src/main/java/com/efub/dhs/domain/member/dto/AuthRequestDto.java
  src/main/java/com/efub/dhs/domain/member/dto/AuthResponseDto.java
  src/main/java/com/efub/dhs/domain/member/dto/SignUpResponseDto.java
  src/main/java/com/efub/dhs/domain/member/repository/MemberRepository.java
  src/main/java/com/efub/dhs/domain/member/service/AuthService.java
  src/main/java/com/efub/dhs/domain/member/service/MemberUserDetailsService.java
  src/main/java/com/efub/dhs/global/config/AuthenticationConfig.java
  src/main/java/com/efub/dhs/global/config/OpenApiConfig.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
  src/main/java/com/efub/dhs/global/jwt/auth/JwtAuthProvider.java
  src/main/java/com/efub/dhs/global/jwt/auth/JwtFilter.java
  src/main/java/com/efub/dhs/global/jwt/entity/JwtToken.java
  src/main/java/com/efub/dhs/global/jwt/repository/JwtRepository.java
  src/main/java/com/efub/dhs/global/jwt/service/JwtService.java
  src/main/java/com/efub/dhs/global/jwt/utils/JwtUtils.java
  src/main/java/com/efub/dhs/global/utils/SecurityUtils.java
Labels: 🔧 기능

#12 [DEPLOY] 배포 환경에 Redis 추가
  .github/workflows/deploy.yml
  docker/Dockerfile
  docker/docker-compose.prod.yml
Labels: 🔫 배포

#23 [FEAT] 멤버 정보 조회 API
  src/main/java/com/efub/dhs/domain/member/controller/AuthController.java
  src/main/java/com/efub/dhs/domain/member/controller/MemberController.java
  src/main/java/com/efub/dhs/domain/member/dto/ProfileResponseDto.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
Labels: 🔧 기능

#21 [FEAT] 카카오 로그인 기능 추가
  src/main/java/com/efub/dhs/DhsApplication.java
  src/main/java/com/efub/dhs/domain/member/controller/OAuthController.java
  src/main/java/com/efub/dhs/domain/member/dto/KakaoOAuthRequestDto.java
  src/main/java/com/efub/dhs/domain/member/service/KakaoOAuthService.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
  src/main/java/com/efub/dhs/global/feign/client/KakaoTokenClient.java
  src/main/java/com/efub/dhs/global/feign/client/KakaoUserInfoClient.java
  src/main/java/com/efub/dhs/global/feign/dto/request/KakaoTokenRequestDto.java
  src/main/java/com/efub/dhs/global/feign/dto/response/KakaoTokenResponseDto.java
  src/main/java/com/efub/dhs/global/feign/dto/response/KakaoUserInfoResponseDto.java
Labels: 🔧 기능

#20 [FEAT] 행사 상세 조회 기능
  src/main/java/com/efub/dhs/domain/heart/repository/HeartRepository.java
  src/main/java/com/efub/dhs/domain/heart/service/HeartService.java
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/GoalDto.java
  src/main/java/com/efub/dhs/domain/program/dto/HostDto.java
  src/main/java/com/efub/dhs/domain/program/dto/ImageDto.java
  src/main/java/com/efub/dhs/domain/program/dto/NoticeDto.java
  src/main/java/com/efub/dhs/domain/program/dto/ProgramDetailResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/ProgramDto.java
  src/main/java/com/efub/dhs/domain/program/dto/ProgramMemberDto.java
  src/main/java/com/efub/dhs/domain/program/dto/ProgramOutlineResponseDto.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/domain/program/repository/NoticeRepository.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramImageRepository.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/domain/registration/repository/RegistrationRepository.java
  src/main/java/com/efub/dhs/domain/registration/service/RegistrationService.java
Labels: 🔧 기능

#32 [FEAT] 좋아요한 행사 리스트 조회 API
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/PageInfoDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramLikedResponseDto.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramMemberService.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
Labels: 🔧 기능

#25 [FEAT] 행사 등록 API
  docker/docker-compose.dev.yml
  src/main/java/com/efub/dhs/domain/member/entity/Member.java
  src/main/java/com/efub/dhs/domain/member/service/KakaoOAuthService.java
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/PageInfoDto.java
  src/main/java/com/efub/dhs/domain/program/dto/request/ProgramCreationRequestDto.java
  src/main/java/com/efub/dhs/domain/program/dto/request/ProgramRegistrationRequestDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramCreationResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramDetailResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramLikedResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramOutlineResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramRegistrationResponseDto.java
  src/main/java/com/efub/dhs/domain/program/entity/Category.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramMemberService.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/domain/registration/entity/Registration.java
  src/main/java/com/efub/dhs/domain/registration/service/RegistrationService.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
Labels: 🔧 기능

#30 [FEAT] 행사 좋아요 API
  src/main/java/com/efub/dhs/domain/heart/controller/HeartController.java
  src/main/java/com/efub/dhs/domain/heart/dto/HeartRequestDto.java
  src/main/java/com/efub/dhs/domain/heart/dto/HeartResponseDto.java
  src/main/java/com/efub/dhs/domain/heart/entity/Heart.java
  src/main/java/com/efub/dhs/domain/heart/service/HeartService.java
Labels: 🔧 기능

#34 [FEAT] CORS 설정 추가
  docker/docker-compose.dev.yml
  src/main/java/com/efub/dhs/global/config/CorsConfig.java
Labels: 🔧 기능

#35 [FEAT] 등록한 행사 리스트 조회 API
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramCreatedResponseDto.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramMemberService.java
Labels: 🔧 기능

#40 [FIX] 로그아웃 에러 해결
  src/main/java/com/efub/dhs/domain/member/controller/AuthController.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
  src/main/java/com/efub/dhs/global/jwt/entity/JwtToken.java
  src/main/java/com/efub/dhs/global/jwt/service/JwtService.java
Labels: 🐞 버그

#42 [FIX] CORS 오류 해결
  src/main/java/com/efub/dhs/global/config/CorsConfig.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
Labels: 🐞 버그

#36 [FEAT] 행사 리스트 조회 API
  build.gradle
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/ProgramDto.java
  src/main/java/com/efub/dhs/domain/program/dto/request/ProgramListRequestDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramOutlineResponseDto.java
  src/main/java/com/efub/dhs/domain/program/entity/Category.java
  src/main/java/com/efub/dhs/domain/program/entity/Sort.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepositoryCustom.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepositoryImpl.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/global/config/QueryDslConfig.java
Labels: 🔧 기능

#38 [FEAT] 인기 행사 리스트 조회 API
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
Labels: 🔧 기능

#46 [FEAT] 공지사항 등록 API
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/request/NoticeCreationRequestDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/NoticeCreationResponseDto.java
  src/main/java/com/efub/dhs/domain/program/service/NoticeService.java
Labels: 🔧 기능

#47 [FEAT] 행사 마감 API
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
Labels: 🔧 기능

#48 [FEAT] 행사 참가 신청
  src/main/java/com/efub/dhs/domain/heart/service/HeartService.java
  src/main/java/com/efub/dhs/domain/member/service/AuthService.java
  src/main/java/com/efub/dhs/domain/member/service/MemberService.java
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramRegisteredResponseDto.java
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramRegistrationResponseDto.java
  src/main/java/com/efub/dhs/domain/program/entity/Category.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramMemberService.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/domain/registration/controller/RegistrationController.java
  src/main/java/com/efub/dhs/domain/registration/dto/RegistrationModificationRequestDto.java
  src/main/java/com/efub/dhs/domain/registration/entity/RefundStatus.java
  src/main/java/com/efub/dhs/domain/registration/entity/Registration.java
  src/main/java/com/efub/dhs/domain/registration/service/RegistrationService.java
  src/main/java/com/efub/dhs/global/jwt/service/JwtService.java
  src/main/java/com/efub/dhs/global/utils/SecurityUtils.java
Labels: 🔧 기능

#52 [FIX] 인증 정보 찾지 못했을 경우 예외를 던지지 않고 null 리턴
  src/main/java/com/efub/dhs/global/utils/SecurityUtils.java
Labels: 🐞 버그

#55 [FIX] 로그인 없이 행사 조회 가능하도록 수정
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/global/config/SecurityConfig.java
Labels: 🐞 버그

#57 [FIX] 카테고리 수정
  src/main/java/com/efub/dhs/domain/program/entity/Category.java
Labels: 🐞 버그

#58 [FEAT] S3 이미지 업로드
  build.gradle
  src/main/java/com/efub/dhs/domain/program/controller/ProgramController.java
  src/main/java/com/efub/dhs/domain/program/dto/request/ProgramCreationRequestDto.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
  src/main/java/com/efub/dhs/domain/program/entity/ProgramImage.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramImageService.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
  src/main/java/com/efub/dhs/global/config/S3Config.java
Labels: 🔧 기능

#62 [FIX] 타임존 KST로 변경
  src/main/java/com/efub/dhs/DhsApplication.java
Labels: 🐞 버그

#59 [FIX] 비슷한 행사 리스트, 인기 행사 리스트 로직 수정
  src/main/java/com/efub/dhs/domain/program/dto/response/ProgramOutlineResponseDto.java
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
Labels: 🐞 버그

#65 [FIX] 좋아요 생성 시 Program의 likeNum 증가하도록 수정
  src/main/java/com/efub/dhs/domain/heart/service/HeartService.java
  src/main/java/com/efub/dhs/domain/program/entity/Program.java
Labels: 🐞 버그

#66 [REFACTOR] 비슷한 행사, 인기 행사 리스트 조회
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
  src/main/java/com/efub/dhs/domain/program/service/ProgramService.java
Labels: 🔧 기능

#68 [FIX] 찜 취소 시 찜 목록에서 삭제하도록 수정
  src/main/java/com/efub/dhs/domain/program/repository/ProgramRepository.java
Labels: 🐞 버그
